# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-20 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.CharField(blank=True, choices=[('tech', 'tech'), ('life', 'life')], max_length=500, null=True),
        ),
    ]
